### ISSUE TITLE
xvfbwrapper.py:93 cygwin/win32 compatibility

### ISSUE THREAD

**Issue by mklump** [cgoldberg/xvfbwrapper#18]
I recommend adding addition handling in xvfbwrapper.py on line 93 to include running on a win32/cygwin setup by also including looking for the executable 'xvfb-run', not just 'Xvfb' where 'Xvfb' hard string is the default for compatibility to the win32 OS and cygwin\bin binary bits version of Xvfb is installed.

**Comment by cgoldberg** [comment]
thanks... I'll take a look.
pull requests are always welcomed
