### ISSUE TITLE
xvfbwrapper.py:57 cygwin/win32 compatibility

### ISSUE THREAD

**Issue by mklump** [cgoldberg/xvfbwrapper#19]
I recommend on line 57 setting the keyword argument close_fds=False as the fourth positional argument in the function call to self.proc = subprocess.Popen() checking and/or if: block handling to maintain correct/better compatibility to the win32 OS with cygwin\bin version of Xvfb that is installed.

**Comment by cgoldberg** [comment]
pull requests are welcome.  I don't have a Windows machine to test on.
