### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pelme** [cgoldberg/xvfbwrapper#25]
The last release on PyPI is a bit dated and does not include the file locking for getting unique displays.

Let me know if there is anything I can do to help!

**Comment by pelme** [comment]
Is there anything I can do to help this move forward?

**Comment by cgoldberg** [comment]
thanks for the reminder.  sorry for the delay... I will get to this in the next few days.

**Comment by pelme** [comment]
No problem and thanks for a very useful tool!

**Comment by cgoldberg** [comment]
done.
0.2.9 is up on PyPI! 

 https://pypi.python.org/pypi/xvfbwrapper

**Comment by pelme** [comment]
Thank you! ✨
