### ISSUE TITLE
Does not work as dependency - problems with easyinstall

### ISSUE THREAD

**Issue by alkuzad** [cgoldberg/xvfbwrapper#33]
```bash
mkdir test
cd test

cat << 'EOF' > setup.py
from setuptools import setup

setup(name='test', version='test', description='test', py_modules=['test'],
      install_requires=['xvfbwrapper'])
EOF

cat << 'EOF' > test.py
print("Module test is working and installed")
EOF

python setup.py install
python -mtest # Should output "print("Module test is working and installed")"
```

Instead easy_install prints error:

```
Best match: xvfbwrapper 0.2.9
Processing xvfbwrapper-0.2.9.tar.gz
Writing /tmp/easy_install-yl6fus8n/xvfbwrapper-0.2.9/setup.cfg
Running xvfbwrapper-0.2.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yl6fus8n/xvfbwrapper-0.2.9/egg-dist-tmp-ih2vd38w
zip_safe flag not set; analyzing archive contents...
No eggs found in /tmp/easy_install-yl6fus8n/xvfbwrapper-0.2.9/egg-dist-tmp-ih2vd38w (setup script problem?)
```

**Comment by cgoldberg** [comment]
use pip?

**Comment by alkuzad** [comment]
easy_install is builtin to setuptools and it's used by it internally to manage building/testing process. Of course I can install xvfbwrapper via pip manually but it's workaround as dependency has to be removed from pypi package and explictly marked in docs "Hey, it depends on xvfbwrapper but you have to install it separatelly". I would like to create pypi package that someone can install and continue, without any problems.

**Comment by cgoldberg** [comment]
I could install your "test" example using 'pip install .' but it fails with
'python setup.py install'.

I don't have much time for supporting this project, but happy to merge a PR
if you can fix... or help diagnose the cause of the setup issue.
